### ISSUE TITLE
Work detailview: add edit for genre group and genre

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#14]
The work detail view should be added and should be made visible when a work in work list view is clicked upon. 

All Worksfields should be made visible, as well as the genres and genre groups.

 made possible to add a genre group or genre to a work. 
Possibly the model needs to be changed. 

add edit for genre group and genre

**Comment by Mergpijp** [comment]
This is done

**Comment by Mergpijp** [comment]
There is a separate view to add genre/genre groups
