### ISSUE TITLE
Search: create functionality/button to search ONLY for authors

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#16]
In the existing search functionality a button should be added with which the user should be able to search only for authors.

**Comment by Mergpijp** [comment]
The page dictates which search is to be used is that what you mean?

**Comment by ThijsRU** [comment]
How is this done in Global Orthodoxy? With a button?

**Comment by ThijsRU** [comment]
Even overleggen anders?

**Comment by Mergpijp** [comment]
done
