### ISSUE TITLE
Check outcome scrape

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#21]
The results of the scrape have to be checked in order to be sure that all information of each FA is imported and the lemma parts (alias, name and date) are separated and placed in the right fields. 
Seek out what the issues are when it is not working or if some things can be placed in the database cleaner, with little time, for instance the ", " in the name. Some authors only have an alias, view for instance Albertus Debolecki Polaccus (fl. late 16th-early 17th cent.)

**Comment by Mergpijp** [comment]
This seems done.
