### ISSUE TITLE
Add Literature to Author View

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#22]
The Literature that is scraped from the old site needs to be shown in the Author view, under Works.

**Comment by Mergpijp** [comment]
You mean the detail view right? Peculair that it has not been scraped correctly or is still a old database I have been working with.

**Comment by ThijsRU** [comment]
Probably the literature is scraped correctly but is placed in Additional info or am I wrong?

**Comment by ThijsRU** [comment]
This has been done
