### ISSUE TITLE
Scrape data old site, import them in the database of the new site

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#6]
First the the data of the old site needs to be scraped. Some parts can be placed, if possible, in a specific field of a specific table such as the first part in `name` in the `Author` table, the second name (after the "(" if there is one!) in `alias` in the `Alias` table and the indication of the time period in the last part of each lemma in 'date' in the `Location_time` table. 

The "vitae", the text between the name of the FA and "Works" should be placed in the `biography` field of the `Author` table. 

The text under "Works" should be placed in its entirety in the `text` field of the `Works' table.

The text under "Literature" should be placed in the `Additional_info` table, in the `Add_comments` field.

**Comment by Mergpijp** [comment]
I see that I did this for the large part correctly. Only I put the time period in the date_precision birt/death. I think you are describing it wrong?
