### ISSUE TITLE
Check forms, edit functionality

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#7]
After the data from the old site are placed into the database, the forms that are created to edit the data need to be checked. 

This can be done by using a number of original FA authors or by the creation of new ones, the first option is preferable. 

All fields that are in the database need to be filled and tested to see if everything works as planned as the PI will need to edit all of the original records ans subdivide large texts into a number of tables and fields.

**Comment by Mergpijp** [comment]
There is a strange bug were I cannot assign the variable alias it will return None. I tried renaming the variable but the view still not showing linked aliases.

**Comment by Mergpijp** [comment]
Turned out to be a name issue in the div that is getting updated. The question remains for works were are all the texts? I think I will make the variable text available.
