### ISSUE TITLE
Create Affiliation table

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#8]
It seems that there is no place right now in the database for the information on the affiliation ('orde') of each FA. In a separate table it should be made possible to add each unique affiliation and link a FA to this table FA from the Author table or via a many-to-many table in case one FA has more than 1 affiliation.

**Comment by ThijsRU** [comment]
Or add `affiliation` table in Author

**Comment by Mergpijp** [comment]
done
