### ISSUE TITLE
Create search functionality

### ISSUE THREAD

**Issue by ThijsRU** [Mergpijp/franciscanauthors#9]
The required search functionality is still at bit vague, I have asked the PI for a priority list. 

For now:

- Search for the name of a specific FA
- Search for a work
- Search for genres, sub genres (of works)

Overall presentation of results: list with limited fields, when clicked upon: detail view of the FA (with ALL information). Maybe result for the search for a FA is only a detail view but I think you also want to have a list in some searches.

Original request:

_Searches for author names should bring results of both the Franciscan author name and possible aliases, the affiliation, the period and relevant (dated) locations for context. Normally, when looking for an author, all the relevant information concerning the author will appear (as in the present site): names/aliasses/order affiliation/biographical info/all works/later publications

Searches for works (i.e. works of Franciscan authors) should offer the titles, alternative titles, the authors and the genre . It should be possible to limit the search for periods, and genres.

It should be possible to search and filter works on genre, location and period only._

**Comment by Mergpijp** [comment]
Ok but now that I read I think search for genres is integrated in the search for works.

**Comment by ThijsRU** [comment]
That is precisely as we have discussed. Great work!

**Comment by Mergpijp** [comment]
Yes does the works detail view also need to show genre_group linked to genre? genre is already shown

**Comment by ThijsRU** [comment]
Yes, the genre group should also be visible.
